#!/usr/bin/env python3
"""Generate browser-ready U.S. route data from an OpenFlights snapshot."""

import csv
import json
from pathlib import Path


AIRLINES = {
    "AS": "Alaska",
    "AA": "American",
    "DL": "Delta",
    "F9": "Frontier",
    "B6": "JetBlue",
    "WN": "Southwest",
    "NK": "Spirit",
    "SY": "Sun Country",
    "UA": "United",
}


def read_airports(path):
    airports = {}
    with path.open(newline="", encoding="utf-8") as source:
        for row in csv.reader(source):
            code = row[4]
            if row[3] == "United States" and len(code) == 3 and code != r"\N":
                airports[code] = {
                    "code": code,
                    "name": row[1],
                    "city": row[2],
                    "coordinates": [float(row[7]), float(row[6])],
                }
    return airports


def read_routes(path, airports):
    routes = {airline: set() for airline in AIRLINES.values()}
    with path.open(newline="", encoding="utf-8") as source:
        for row in csv.reader(source):
            airline = AIRLINES.get(row[0])
            origin, destination = row[2], row[4]
            if airline and origin in airports and destination in airports:
                routes[airline].add(tuple(sorted((origin, destination))))
    return {airline: sorted(network) for airline, network in routes.items()}


def main():
    root = Path(__file__).resolve().parents[1]
    airports = read_airports(Path("/tmp/openflights-airports.dat"))
    routes = read_routes(Path("/tmp/openflights-routes.dat"), airports)
    used_codes = {code for network in routes.values() for route in network for code in route}
    used_airports = {code: airports[code] for code in sorted(used_codes)}

    output = [
        "// Generated by scripts/generate-route-data.py from the OpenFlights snapshot.",
        "// Routes are non-stop U.S. segments for the selected operating carriers.",
        f"const ROUTE_AIRPORTS = {json.dumps(used_airports, separators=(',', ':'))};",
        f"const ROUTE_NETWORKS = {json.dumps(routes, separators=(',', ':'))};",
        "",
    ]
    (root / "route-data.js").write_text("\n".join(output), encoding="utf-8")


if __name__ == "__main__":
    main()
